imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SBCPlatformBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
   
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }




# FOSUser Configuration
fos_user:
    db_driver:     orm                       
    # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      
    # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    UserBundle\Entity\User 
    # La classe de l'entité User que nous utilisons
    #autoriser l'envoie de mail si reset password

    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: you@example.com
        sender_name: You
    

# Stof\DoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Assetic            
assetic:
    #node: /usr/bin/nodejs
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:
        - "SBCPlatformBundle"
        - "FOSUserBundle"
    filters:
        cssrewrite: ~
        jpegoptim:
            bin: /usr/local/bin/jpegoptim
            max: 20
            apply_to: "\.jpg$"
    twig:
        functions:
            jpegoptim: ~

#VichUploader
vich_uploader:
    db_driver: orm

    mappings:
        materiel_facture:
            uri_prefix:         /demos/materiel/web/fichiers/factures/materiels
            upload_destination: '%kernel.root_dir%/../web/fichiers/factures/materiels'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:
                service: vich_uploader.namer_property
                options: { property: 'name'}


        materiel_fichiers:
            uri_prefix:         /demos/materiel/web/fichiers/autres/materiels
            upload_destination: '%kernel.root_dir%/../web/fichiers/autres/materiels'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
#Autocomplete
tetranz_select2_entity:
    language: fr
    scroll: true