<?php

namespace SBCPlatformBundle\Repository;

/**
 * ChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierRepository extends \Doctrine\ORM\EntityRepository
{

    public function getChantiers()
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.creationdate', 'DESC')
            ->getQuery();

        return $query
            ->getResult();
    }

   

}
