<?php

namespace SBCPlatformBundle\Repository;


/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
   

    /**
     * Search professions by reg
     * @param $reg
     * @return array
     */
    public function findByReg($reg)
    {
        $qb = $this->createQueryBuilder('d');
        return $qb->where(
            $qb->expr()->like('d.name', ':name')
        )
            ->setParameter('name', '%' . $reg . '%')
            ->getQuery()
            ->getResult();
    }
}
