<?php

namespace SBCPlatformBundle\Repository;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * Search professions by reg
     * @param $reg
     * @return array
     */
    public function findByReg($reg)
    {
        $qb = $this->createQueryBuilder('c');
        return $qb->where(
            $qb->expr()->like('c.name', ':name')
        )
            ->setParameter('name', '%' . $reg . '%')
            ->getQuery()
            ->getResult();
    }
}
