<?php

namespace SBCPlatformBundle\Repository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInterventions()
    {
        $query = $this->createQueryBuilder('i')
            ->leftJoin('i.typeintervention', 'ti')
            ->addSelect('ti')
            ->leftJoin('ti.natureintervention', 'ni')
            ->addSelect('ni')
            ->leftJoin('ti.materiel', 'm')
            ->addSelect('m')

            ->leftJoin('i.interferedby', 'o')
            ->addSelect('o')

            ->orderBy('i.creationdate', 'DESC')
            ->getQuery();

        return $query
            ->getResult();
    }


    public function getIntervention($id)
    {

        $query = $this->createQueryBuilder('i')
          ->addSelect('i')
            ->leftJoin('i.typeintervention', 'ti')
            ->addSelect('ti')
            ->leftJoin('i.interferedby', 'o')
            ->addSelect('o')

            ->leftJoin('ti.materiel', 'm')
            ->addSelect('m')
            ->leftJoin('ti.natureintervention', 'ni')
            ->addSelect('ni')

            ->where('i.id = ?1')
            ->setParameters(array(1 => $id));


        return $query->getQuery()->getOneOrNullResult();
    }
}
