<?php

namespace SBCPlatformBundle\Repository;

/**
 * NatureInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureInterventionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Search ntures by reg
     * @param $reg
     * @return array
     */
    public function findByReg($reg)
    {
        $qb = $this->createQueryBuilder('ni');
        return $qb->where(
            $qb->expr()->like('ni.name', ':name')
        )
            ->setParameter('name', '%' . $reg . '%')
            ->getQuery()
            ->getResult();
    }
}
