<?php

namespace SBCPlatformBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNotifications()
    {
        $query = $this->createQueryBuilder('no')

//            ->where('no.seen = 0')
            ->orderBy('no.creationdate', 'DESC')
            ->getQuery();

        return $query
            ->getResult();
    }

    public function getNotification($id)
    {

        $query = $this->createQueryBuilder('no')

            ->where('no.id = ?1')
            ->getQuery()
            ->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }


    public function getSomeNotifications()
    {
        $query = $this->createQueryBuilder('no')

//            ->where('no.seen = 0')
            ->orderBy('no.creationdate', 'DESC')
            ->setMaxResults(10)
            ->getQuery();

        return $query
            ->getResult();
    }

    public function setNotificationsSeen()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->update('SBCPlatformBundle:Notification','no')
            ->set('no.seen','true')

            ->getQuery();

        return $query
            ->getResult();
    }

}
