<?php

namespace SBCPlatformBundle\Repository;

/**
 * OuvrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvrierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOuvriers()
    {
        $query = $this->createQueryBuilder('o')
            ->orderBy('o.name', 'ASC')
            ->getQuery();

        return $query
            ->getResult();
    }

    /**
     * Search professions by reg
     * @param $reg
     * @return array
     */
    public function findByReg($reg)
    {
        $qb = $this->createQueryBuilder('o');
        return $qb->where(
            $qb->expr()->like('o.name', ':name')
        )
            ->setParameter('name', '%' . $reg . '%')
            ->getQuery()
            ->getResult();
    }

    public function generateCode()
    {

        $query = $this->createQueryBuilder('o')
            ->orderBy('o.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if ($query == null) {

            return '00001';
        }

        return str_pad($query->getId() + 1, 5, "0", STR_PAD_LEFT);  ;

    }
}
