<?php

namespace SBCPlatformBundle\Repository;

/**
 * PlanificationPreventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationPreventionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        $query = $this->createQueryBuilder('i')
            ->addSelect('i')
            ->leftJoin('i.materiel', 'materiel')
            ->addSelect('materiel')
            ->leftJoin('i.natureintervention', 'natureintervention')
            ->addSelect('natureintervention')
            ->orderBy('i.creationdate', 'DESC')
            ->getQuery();

        return $query
            ->getResult();
    }


    public function find($id, $lockMode = null, $lockVersion = null)
    {

        $query = $this->createQueryBuilder('i')
            ->addSelect('i')
            ->leftJoin('i.materiel', 'materiel')
            ->addSelect('materiel')
            ->leftJoin('i.natureintervention', 'natureintervention')
            ->addSelect('natureintervention')
            ->where('i.id = ?1')
            ->setParameters(array(1 => $id));

        return $query->getQuery()->getOneOrNullResult();
    }
}
