<?php

namespace SBCPlatformBundle\Repository;

/**
 * PointageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPointages()
    {

        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.materiel', 'm')
            ->addSelect('m')

            ->leftJoin('p.pointedby', 'o')
            ->addSelect('o')
            ->leftJoin('p.emplacement', 'e')
            ->addSelect('e')
            ->orderBy('p.creationdate', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function getPointage($id)
    {

        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.materiel', 'm')
            ->addSelect('m')
            ->leftJoin('p.pointedby', 'o')
            ->addSelect('o')
            ->leftJoin('p.emplacement', 'e')
            ->addSelect('e')
            ->where('p.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }

    public function getPointagesParEmplacement()
    {

        $query = $this->createQueryBuilder('p')
            ->addSelect('p, SUM(p.usedduration) as totale')
            ->addSelect('p')
            ->groupBy('p.emplacement')
            ->addGroupBy('p.materiel')
            ->leftJoin('p.materiel', 'm')
            ->addSelect('m')
            ->leftJoin('p.emplacement', 'e')
            ->addSelect('e')
            ->getQuery();

        return $query->getResult();
    }

}